# Generated by Django 3.1.7 on 2021-03-03 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('user_type', models.CharField(choices=[('A', 'Admin'), ('D', 'Doctor'), ('R', 'Receptionist'), ('L', 'lab')], max_length=1)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Consultants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Fees', models.PositiveIntegerField(default=0)),
                ('Gender', models.CharField(max_length=10)),
                ('Dob', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=10)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UhidNo', models.CharField(default=users.models.creatUhid, max_length=100)),
                ('title', models.CharField(max_length=10)),
                ('suraname', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('Age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('tell_no', models.CharField(max_length=10)),
                ('ref_by', models.CharField(max_length=100)),
                ('paymentBy', models.CharField(max_length=10)),
                ('id_proof_name', models.CharField(max_length=100)),
                ('id_prof_details', models.CharField(max_length=20)),
                ('Weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Consultants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.consultants')),
            ],
        ),
    ]
