# Generated by Django 3.1.7 on 2021-03-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210303_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='patient_status',
            field=models.CharField(default='N', max_length=15),
        ),
        migrations.AlterField(
            model_name='patients',
            name='middleName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
