# Generated by Django 3.1.7 on 2021-03-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210304_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='suraname',
            new_name='surname',
        ),
    ]
