# Generated by Django 3.1.7 on 2021-03-03 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Fees', models.PositiveIntegerField(default=0)),
                ('Gender', models.CharField(max_length=10)),
                ('Dob', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=10)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('suraname', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('Age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('tell_no', models.CharField(max_length=10)),
                ('ref_by', models.CharField(max_length=100)),
                ('paymentBy', models.CharField(max_length=10)),
                ('id_proof_name', models.CharField(max_length=100)),
                ('id_prof_details', models.CharField(max_length=20)),
                ('Weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Consultants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.consultants')),
            ],
        ),
    ]
