# Generated by Django 3.1.7 on 2021-03-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210304_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
