# Generated by Django 3.1.7 on 2021-03-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210307_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='Consultants',
        ),
    ]
