# Generated by Django 3.1.7 on 2021-03-07 18:48

from django.db import migrations, models
import django.db.models.deletion
import opd.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210307_2314'),
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billNo', models.CharField(default=opd.models.makeBillNumber, max_length=100)),
                ('isFinalise', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patients')),
            ],
        ),
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.services')),
            ],
        ),
    ]
