# Generated by Django 3.1.7 on 2021-03-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_billdetails_billheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='billheader',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
