# Generated by Django 3.1.7 on 2021-03-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_billheader_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetails',
            name='bill_header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opd.billheader'),
        ),
    ]
