# Generated by Django 3.1.7 on 2021-03-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0004_billdetails_bill_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetails',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='billheader',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billheader',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billheader',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
