# Generated by Django 3.1.7 on 2021-03-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_patients_consultants'),
        ('opd', '0005_auto_20210309_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpdPatients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.consultants')),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patients')),
            ],
        ),
    ]
